name: Build and Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'k8s/**'

permissions:
  contents: write

jobs:
  build:
    runs-on: arc-runners

    steps:
      - uses: actions/checkout@v3

      # ðŸ”¥ LOGIN TO HARBOR (NOT DOCKERHUB)
      - name: Login to Harbor
        run: |
          echo "${{ secrets.HARBOR_TOKEN }}" | docker login r.badshah.io \
            -u "${{ secrets.HARBOR_USERNAME }}" \
            --password-stdin

      # ðŸ”¥ BUILD IMAGE (IMPORTANT: MUST USE HARBOR PATH)
      - name: Build Image
        run: |
          docker build -t r.badshah.io/${{ secrets.HARBOR_USERNAME##*+ }}/demo-app:${{ github.sha }} .

      # ðŸ”¥ PUSH IMAGE
      - name: Push Image
        run: |
          docker push r.badshah.io/${{ secrets.HARBOR_USERNAME##*+ }}/demo-app:${{ github.sha }}

      # ðŸ”¥ UPDATE K8S YAML
      - name: Update Kubernetes Manifest and Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sed -i "s|image:.*|image: r.badshah.io/${{ secrets.HARBOR_USERNAME##*+ }}/demo-app:${{ github.sha }}|g" k8s/deployment.yaml
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git commit -am "Update image tag"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git push
