name: Build and Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'k8s/**'

permissions:
  contents: write

jobs:
  build:
    runs-on: arc-runners

    steps:
      - uses: actions/checkout@v3

      - name: Login to Harbor
        env:
          HARBOR_USER: ${{ secrets.HARBOR_USERNAME }}
          HARBOR_PASS: ${{ secrets.HARBOR_TOKEN }}
        run: |
          echo "$HARBOR_PASS" | docker login r.badshah.io \
            --username "$HARBOR_USER" \
            --password-stdin
      
      - name: Extract project name
        env:
          HARBOR_USER: ${{ secrets.HARBOR_USERNAME }}
        run: |
          PROJECT=$(echo "$HARBOR_USER" | sed 's/^robot\$//' | cut -d'+' -f1)
          echo "PROJECT=$PROJECT" >> $GITHUB_ENV
      
      - name: Build Image
        run: |
          docker build -t r.badshah.io/$PROJECT/demo-app:${{ github.sha }} .
      
      - name: Push Image
        run: |
          docker push r.badshah.io/$PROJECT/demo-app:${{ github.sha }}

      # UPDATE K8S YAML
      - name: Update Kubernetes Manifest and Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sed -i "s|image:.*|image: r.badshah.io/$PROJECT/demo-app:${{ github.sha }}|g" k8s/deployment.yaml
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git commit -am "Update image tag"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git push
